name: gse131907
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scipy
  - statsmodels
  - scanpy
  - anndata
  - pyyaml
  - openpyxl
  - pip
